backend:
  name: github
  repo: cqweb21/cqweb-mirror   # ← 已经改成你的仓库
  branch: main                 # ← 用 main 分支
backend:
  name: github
  repo: cqweb21/cqweb-mirror
  branch: main
publish_mode: simple
locale: zh_CN

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "gb_posts"
    label: "简体文章（Markdown 新内容）"
    folder: "content/gb/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主图", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "big5_posts"
    label: "繁体文章（Markdown 新内容）"
    folder: "content/big5/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主圖", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  # （可选）如果你偶尔需要直接在后台改 HTML，可以打开下面两组：
  # - name: "gb_html"
  #   label: "简体区（直接编辑 HTML）"
  #   folder: "gb"
  #   create: false
  #   extension: "html"
  #   editor: { preview: false }
  #   fields:
  #     - { label: "HTML 源码", name: "body", widget: "code", default: "", output_code_only: true, language: "html" }
  #
  # - name: "big5_html"
  #   label: "繁体区（直接编辑 HTML）"
  #   folder: "big5"
  #   create: false
  #   extension: "html"
  #   editor: { preview: false }
  #   fields:
  #     - { label: "HTML 源码", name: "body", widget: "code", default: "", output_code_only: true, language: "html" }
