backend:
  name: github
  repo: cqweb21/cqweb-mirror
  branch: main
  base_url: https://cqweb21-site.vercel.app
  auth_endpoint: api/auth

publish_mode: simple
locale: zh_CN

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  # === 文章（Markdown） ===
  - name: "gb_posts"
    label: "简体文章（Markdown 新内容）"
    folder: "content/gb/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主图", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "big5_posts"
    label: "繁体文章（Markdown 新内容）"
    folder: "content/big5/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主圖", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  # === 页面：latest.html 由后台直接编辑 ===
  - name: "gb_latest"
    label: "页面：最新更新（简体）"
    files:
      - label: "最新更新页（简体）"
        name: "gb_latest_page"
        file: "gb/latest.html"
        editor:
          preview: false
        fields:
          - label: "HTML 源码"
            name: "body"
            widget: "code"
            output_code_only: true
            language: "html"

  - name: "big5_latest"
    label: "頁面：最新更新（繁體）"
    files:
      - label: "最新更新頁（繁體）"
        name: "big5_latest_page"
        file: "big5/latest.html"
        editor:
          preview: false
        fields:
          - label: "HTML 原始碼"
            name: "body"
            widget: "code"
            output_code_only: true
            language: "html"
