backend:
  name: github
  repo: cqweb21/cqweb-mirror
  branch: main
  # 如果你先用 Vercel 的临时域名测试，就写它：
  base_url: https://cqweb-mirror.vercel.app

publish_mode: simple
locale: zh_CN

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "gb_posts"
    label: "简体文章（Markdown 新内容）"
    folder: "content/gb/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主图", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

  - name: "big5_posts"
    label: "繁体文章（Markdown 新内容）"
    folder: "content/big5/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    format: "frontmatter"
    fields:
      - { label: "標題", name: "title", widget: "string" }
      - { label: "發佈日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ssZ" }
      - { label: "主圖", name: "cover", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
